### ISSUE TITLE
atomic vector

### ISSUE THREAD

**Issue by osturnus** [nicolas-robette/GDAtools#1]
Hi, thanks for wonderful package first! Thanks for update!

I stumble upon some error which I'm not able to solve, even with updated R and all packages.
First - a year or more ago I cease to use modif.rate, because it give only one line output with 100%. I had do rewrite it somehow. Now, when I discover new ggplot functions in GDAtools, they are not working. Just getting:

Error in resmca$eig$mrate : $ operator is invalid for atomic vectors

These issues seems to be connected.
Thanks

**Comment by nicolas-robette** [comment]
Could it be that you use a MCA object computed with FactoMineR package ? If it's not the case, could you post a reproducible example ?

Anyway, I'll fix "modif.rate" and "ggcloud_*" functions to make them work with MCAs from FactoMineR as well.

Bests,

Nicolas

**Comment by osturnus** [comment]
Yes! That is the case. I didn't know that gdatools uses different MCA object. For a long time I didn't check changes in functionality so I still thought that it is addon to FactoMineR. 
Just to be clear, now it is developed rather as a stand-alone package? If so, which function should be used as an equivalent of FactoMineR's plain MCA?

Thanks a lot for all your work!

**Comment by nicolas-robette** [comment]
GDAtools is intended to be a stand-alone package and I think it's more or less the case now. You can perform a "classic" MCA by using speMCA() function with "excl" argument set to NULL (which is the default).

**Comment by osturnus** [comment]
Thanks! Good to know.
