### ISSUE TITLE
ggadd_supvar and ggrepel

### ISSUE THREAD

**Issue by janhovden** [nicolas-robette/GDAtools#10]
Not sure if this is a feature request or just me being bad at R.

The point is simply that adding supplementary categories by ggadd_supvar to a map leads to their overlap, they are not positioned via ggrepel to increase their readability (see example). This would be a very welcome feature. If this is easily solved by adding +ggrepel() in some way to the object, or another way, I have not figured it out yet.

Jan Fredrik Hovden

<img width="1259" alt="regionpassive32ny" src="https://user-images.githubusercontent.com/17220766/171826363-fe8060e5-d421-4be4-b800-7aaf0ef8a3fe.png">

**Comment by nicolas-robette** [comment]
Supplementary variables already use ggrepel. Still, unfortunately, they constitute a distinct layer : ggrepel avoids overlapping for active variables on one side and for supplementary variables on the other side, but not for all of them all together. By now I don't see any way to fix this... But I'll keep it in mind, maybe one day I'll have a brilliant idea !

**Comment by nicolas-robette** [comment]
I've just added a new function, ggadd_supvars, with an "s", that should be better at repelling when there are multiple supplementary variables.

Bests,
Nicolas
