### ISSUE TITLE
request geom_line -> geom_path in ggadd_interaction

### ISSUE THREAD

**Issue by 419kfj** [nicolas-robette/GDAtools#11]
Dear robette,

I am using ggadd_interaction and I faced confusion about the order in which to draw the lines.

The variable categories are ordered by levels in factor, so I want them to be drawn the lines by these levels, not by the order of the coordinates.

I want "ggplot2::geom_line"  for lines 20 and 21 to be "ggplot2::geom_path".

What do you think?

kazuo

**Comment by nicolas-robette** [comment]
I've done the change, thanks for the suggestion !
