### ISSUE TITLE
Sort argument for pem() returns an error if set to FALSE

### ISSUE THREAD

**Issue by antongrau** [nicolas-robette/GDAtools#13]
Hi,
Thank you for the wonderful package.

The pem() function returns an error if sort = FALSE.

"Error in cor$rscore : object of type 'closure' is not subsettable"

This code reproduces the error:

```
library(GDAtools)
data(Music)
pem(Music$Jazz,Music$Age, sort = FALSE)
```

On another note you can possibly increase the speed of the function substantially by exchanging these lines:
```
cont <- t(as.matrix(GDAtools::dichotom(X, out = "numeric"))) %*% 
    diag(W) %*% as.matrix(GDAtools::dichotom(Y, out = "numeric"))

```
with this line

` cont <- xtabs(data = data.frame(X, Y), ~X+Y)
`
But the row and column labels are not the same though.

**Comment by nicolas-robette** [comment]
Thanks for using this package and for your suggestions ! I've just fixed the bug (naming an object "cor" seems a pretty bad idea) and coded with xtabs().

Besides, I'm currently working on splitting GDAtools in 2 : GDAtools will focus exclusively on GDA and every other descriptive statistics tools will be gathered in the brand new "descriptio" package. The latter is already available on github ; I just have to add the handling of missing values and to update the vignette and then I'll submit it to CRAN.
Bests,
Nicolas

**Comment by antongrau** [comment]
Thank you for the quick reply. Will keep an eye on your descriptio package!

**Comment by nicolas-robette** [comment]
`descriptio` is now on CRAN and the ongoing `GDAtools` github version imports it.
Bests,
Nicolas
