### ISSUE TITLE
Tabcontrib produce extremely wide tables in 2.0

### ISSUE THREAD

**Issue by janhovden** [nicolas-robette/GDAtools#14]
Tabcontrib now produces extremely wide tables which wrap and make them not very readable. 

Here is what they used to look like:
<img width="579" alt="Screenshot 2023-04-18 at 07 43 28" src="https://user-images.githubusercontent.com/17220766/232681950-08b32c3a-155f-4998-ae27-5099f8eb4946.png">

This is what they look like now (in Rstudio):
<img width="720" alt="Screenshot 2023-04-18 at 07 44 19" src="https://user-images.githubusercontent.com/17220766/232682073-9d20adbc-dcb4-4454-94b1-b62ebfb2ff3b.png">

Looks like this issue is simply due to the long column titles in this version of GDATOOLS 2.0

Jan Fredrik Hovden

**Comment by nicolas-robette** [comment]
I recently bought a very large screen, so I didn't have this problem !

I've just updated the function with a `shortlabs` option, which should fix this issue. Still, if you want to keep the long labels and have a nice readable display, you may use `DT::datatable(tabcontrib(mca, 1), rownames = NULL)`, for instance.

Bests,
Nicolas

**Comment by janhovden** [comment]
Great, thank you Nicolas! Both for the updated version with the possibility to use short labels and for the tips about using datatable. Both will provide very useful.

Off-topic: "The Dead Ends of Sociogenomics" is a great read - your article was very positively discussed in our seminar on "Sociology and genetics"-seminar for Norwegian Class Researchers network today in Oslo. 

Best,
Jan Fredrik
