### ISSUE TITLE
ggcloud_variables produce blank map with "best" option if axes are specified

### ISSUE THREAD

**Issue by janhovden** [nicolas-robette/GDAtools#15]
Using GDAtools 2.0.1:

Given the standard example, which works fine:
data(Music)
junk <- c("FrenchPop.NA", "Rap.NA", "Rock.NA", "Jazz.NA", "Classical.NA")
mca <- speMCA(Music[,1:5], excl = junk)
ggcloud_variables(mca, points = "best")

However, specifying axes produces a blank map:
ggcloud_variables(mca, points = "best", axes=c(2,1))

Trying "besthv" produces error:
ggcloud_variables(mca, points = "besthv", axes=c(2,1))
Error in eval(e, x, parent.frame()) : object 'condi' not found

However, using "bestv" or "besth" works normally also when specifying axes.

Jan Fredrik

**Comment by nicolas-robette** [comment]
Could you try to uninstall the package, reinstall the very last version and tell me if the problem remains ?
Bests,
Nicolas

**Comment by janhovden** [comment]
Everything works great after installing the latest version of R, updating Rstudio and installing GDAtools via devtools. Thank you very much! 
Jan Fredrik
