### ISSUE TITLE
parse Error in ggaxis_varibles

### ISSUE THREAD

**Issue by 419kfj** [nicolas-robette/GDAtools#16]
nicoras,

Thank you for the nice Version 2.0. I think now GDAtools become very powerful!

This error report.

I am using dataset Japanese translated Taste example of Le Roux 2010 books data.
I downloaded it from Prof. Le Roux's Web site and recode it into Japanese. 
Please get it from the following URL.

https://www.evernote.com/shard/s15/sh/f18add8e-fdf5-6b88-ea9e-d049e8da0d14/s4DFM9pu38rWaf-PuM5ahV2a5jK1F3Amkr7SyOFmfjU951zsxKvtenFpeA

I load it and make MCA result and tried to plot a one-dimensional plot by using ggaxis_variables. Then encountered the Error.
It might be related to the geom_text_repel().

```
load("taste_d_J.rda")
.d_J %>% filter(Isup=="Active") -> .d0
.d0 %>% names
.d0 %>% select(3:6) -> .d1

res.speMCA0 <- speMCA(.d1)
res.speMCA0 %>% flip.mca(dim = c(1,2)) -> res.speMCA
```

```
ggaxis_variables(res.speMCA,axis=1,prop="ctr")
```

Error in `ggrepel::geom_text_repel()`:
! Problem while converting geom to grob.
ℹ Error occurred in the 3rd layer.
Caused by error in `parse()`:
! <text>:1:15: unexpected input
1: Art.芸術-パフォーマンス・
                  ^
:
:
:

But anyway I report it. If you use the above Japanese data set, in which same category using "・" and "＆" , which seemed to arise this Error.

best regards.

kazuo

**Comment by nicolas-robette** [comment]
Hi, I've tried your example with the last github version of the package (2.0.1) and it seems to work. Could you try on your computer and tell me if it's ok ?
Bests,
Nicolas

**Comment by 419kfj** [comment]
Nicolas,

Thank you for your quick support.
I checked it and it works well !

May I share this information as v2.0.1 with my colleagues?

kazuo

<img width="424" alt="image" src="https://user-images.githubusercontent.com/8220157/235558241-3b6bb51e-d162-4fd8-9125-da1df8de6042.png">

**Comment by nicolas-robette** [comment]
You definitely can !

**Comment by 419kfj** [comment]
Correction！

When I checked the operation in the morning, I copied ggaxis_variable.R from GitHub's R repository and ran it as ggaxis_variable2 on RStudio.

In the afternoon, when I had time, I installed 2.0.1 from GitHub. This does not work. I get the same error as before.

When I look at the package_info, it is 2.0.1.
```
 V GDAtools * 2.0 2023-05-02 [1] Github (nicolas-robette/GDAtools@85c3553) (on disk 2.0.1)
```
The copy of R/ggaxis_variable.R is fine.

R code included in the PACKAGE, is it the same?

kazuo

**Comment by nicolas-robette** [comment]
I've tried again with R 4.3.0 and a reinstallation of the packages, it still works. Here is the information about my session :

![image](https://user-images.githubusercontent.com/40861887/235767014-94dee0a5-b213-4e5c-8612-f7044cba9d83.png)

Maybe there is some mistake about GDAtools version in your installation. Then you would have to uninstall the package, restart R, install the package from github and restart R again.

Bests,
Nicolas

**Comment by 419kfj** [comment]
Nicolas,

As your point out, I encountered an installation error.

```
Error: Failed to install 'GDAtools' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/processx/R/processx.rdb' is corrupt
```
My R was 4.0, so I updated to 4.3.0.

After that, I checked the GDAtools 2.0.1 was installed properly and confirmed that ggaxis_variable works.

Thank you again!
Thank you for your nice tools.

kazuo
