### ISSUE TITLE
missing "indsup" function on Package 'GDAtools' April 2023

### ISSUE THREAD

**Issue by 419kfj** [nicolas-robette/GDAtools#17]
Nicolas,

I try to check the function 'indsup' in the document "Package 'GDAtools' April 2023", but I couldn't find it.

When I use explor::explor with supplementary individuals I use this fuction.
https://juba.github.io/explor/articles/introduction_en.html#gdatools-functions

regards.

kazuo

**Comment by nicolas-robette** [comment]
The "indsup" function has been renamed to "supind" in the last versions of the package.
Bests,
Nicolas
