### ISSUE TITLE
ggadd_supvars produces error message Error in `$<-.data.frame` ...

### ISSUE THREAD

**Issue by janhovden** [nicolas-robette/GDAtools#18]
I am not certain that this is a bug, it probably has to do with some specific requirements for the supplementary data frame which is a bit unclear to me. ggadd_supvars works fine with the Music data in the manual.

When I run ggadd_supvars with my own data, I tend to receive this error message:

mca<- speMCA(rom, excl=ekskluder) 
p <- ggcloud_variables(mca) 
p <- ggadd_supvars(p, mca, supl_new)

Error in `$<-.data.frame`(`*tmp*`, "categories", value = c("0", "1", "0",  :   replacement has 2 rows, data has 80

So I just wonder what likely produces this error message, and how to avoid it. Is this just a problem with NAs in the supplementary data frame, or (likely) something else?

all the best,
Jan Fredrik

A bit more info about the mca and dataframes below:

> levels(rom$breakingbad)
[1] "breakingbad"    "breakingbadNEI"

> str(rom)
'data.frame':	1352 obs. of  44 variables:
 $ beforeigners        : Factor w/ 3 levels "beforeigners",..: 1 2 2 2 2 2 2 2 2 2 ...
 $ blackmirror         : Factor w/ 2 levels "blackmirror",..: 2 1 1 2 2 2 1 1 1 2 ...
 $ breakingbad         : Factor w/ 2 levels "breakingbad",..: 2 2 2 2 2 2 1 1 2 2 ...
 $ broen               : Factor w/ 2 levels "broen","broenNEI": 2 2 2 1 2 2 1 2 2 2 ...
 $ chernobyl           : Factor w/ 2 levels "chernobyl","chernobylNEI": 2 2 1 1 2 2 1 1 2 2 ...

> dim(mca$ind$coord)
[1] 1352    5

> levels(supl_new$BetterCallSaul)
[1] "0" "1"

> str(supl_new)
'data.frame':	1352 obs. of  40 variables:
 $ BetterCallSaul    : Factor w/ 2 levels "0","1": 1 1 NA 1 1 NA 1 1 1 1 ...
 $ BrooklynNineNine  : Factor w/ 2 levels "0","1": 1 1 NA 1 1 NA 1 1 1 1 ...
 $ ExontheBeach      : Factor w/ 2 levels "0","1": 1 1 NA 1 1 NA 1 1 2 1 ...
 $ Friends_A         : Factor w/ 2 levels "0","1": 1 1 NA 1 1 NA 1 1 1 1 ...

PS. (I also would very much to only plot supplementary variables with cos2> a specific value, which does not seem to be a option, but that is another problem. I´ll guess I can just use the supvars command to make a frame with its cos2 values, and then filter on that).

**Comment by nicolas-robette** [comment]
I'm reacting a bit late, sorry. I initially thought it could come from the NAs in your supplementary variables, but I've tried to add some in the Taste example and it works fine. So I'm afraid I don't know...

Adding a filter according to cos2 is definitely a good idea, I'll think about it !

**Comment by nicolas-robette** [comment]
I have just added an option to ggadd_supvars() to filter according to cos2, and a vlab option in ggaxis_variables() : thanks again for the suggestions.

Bests,
Nicolas

**Comment by janhovden** [comment]
Thank you! This will prove very useful - and time saving! For many of us whose skills in R are at a intermediate level, such options saves us a lot of time which would else have been used with fiddling with dplyr and ggplot to get what we want, instead of working sociologically with our data.
