### ISSUE TITLE
It seems modif.rate is not working

### ISSUE THREAD

**Issue by ljkhalil** [nicolas-robette/GDAtools#2]
in modif.rate the vector   is not properly extracted from resmca: 

Original 
e <- resmca$eig[[1]][resmca$eig[[1]]>=seuil]

Proposed changes: 
e <- resmca[["eig"]][,1]
    e<- e[ e >= seuil]

**Comment by nicolas-robette** [comment]
I've just rewritten the function to make it :
- compute raw rates and modified rates
- compatible with objects of classes MCA, speMCA, csMCA, stMCA and multiMCA.
