### ISSUE TITLE
dimdescr produce error of unused argument (dec = c(3, 3, 3, 3))

### ISSUE THREAD

**Issue by janhovden** [nicolas-robette/GDAtools#23]
A problem in GDAtools 2.0.1:

data(Music)
junk <- c("FrenchPop.NA", "Rap.NA", "Rock.NA", "Jazz.NA", "Classical.NA")
mca <- speMCA(Music[,1:5], excl = junk)
# description of the dimensions
dimdescr(mca, limit = 0.1, nperm = 10)

Produces the error:
Error in descriptio::condesc(resmca$ind$coord[, dim[i]], X, weights = resmca$call$row.w,  : 
  unused argument (dec = c(3, 3, 3, 3))

Jan Fredrik

**Comment by nicolas-robette** [comment]
This is now fixed in the last version, thanks.
Bests,
Nicolas
