### ISSUE TITLE
few other suggestions

### ISSUE THREAD

**Issue by osturnus** [nicolas-robette/GDAtools#5]
Hi,

and two other suggestions that could enhance how ggadd_supvar work with size of geom_points...
1) when using prop parameter, maybe scale_size_area() should be added to ensure, that there is natural reference to zero size. E.g. currently, when you would plot only two data point of size e.g. 250 and 260, it would draw points of vastly different size, as it is scaled relatively. But I think the expectation is that they should be almost similar in size (as there is absolute reference point of zero). I'm not sure if it is also case of other prop parameter, but it is the case of "n".

2) When not using prop, it would be nice to be able to scale size of points. (or maybe even the prop size would be nice to be scalable.

Thanks!!!

**Comment by nicolas-robette** [comment]
Thanks for your suggestions, they are now in the new version of the function.
