### ISSUE TITLE
speMCA for the data include zero count factor data cause the error

### ISSUE THREAD

**Issue by 419kfj** [nicolas-robette/GDAtools#6]
I made sample data as follow.

`set.seed(1234)`
`ABC <- c("A","B","C")`
`abc <- c("a","b","c","d")`
`I12 <- c("1","2")`
`data.frame(V1 = sample(ABC,size = 100,replace = TRUE),`
`          V2 = sample(abc,size = 100,replace = TRUE),`
`          V3 = sample(I12,size = 100,replace = TRUE)) %>% mutate_all(.funs = factor) -> .d`
`.d`
`summary(.d)`
`res.speMCA <- speMCA(.d)`
`ggcloud_variables(res.speMCA)`

next, I remove V2 is "d" and do _speMCA_

`.d %>% filter(V2 != "d") -> .d2`
`res.speMCA2 <- speMCA(.d2)`

Then I encounter the error message as folloing.

> svd(H0t) でエラー: infinite or missing values in 'x'
                     (Error)

I tried _FactoMineR::MCA_ to this dataframe, .d2, I got the result.

I think it is bug of speMCA.

So I am using _FactoMineR::MCA_  with excl = <position of junc category> as specific MCA.

regards.

**Comment by nicolas-robette** [comment]
This is because, after the filtering, V2 variable has an empty level (i.e. a level with no observation). I'll fix that for the next version.
In the mean time, you can add this to your script.
`for(i in 1:ncol(.d2)) .d2[,i] <- factor(.d2[,i])`
Best regards,
Nicolas
