### ISSUE TITLE
Question on tabcontib, value ctrtot

### ISSUE THREAD

**Issue by 419kfj** [nicolas-robette/GDAtools#7]
Now I am using your nice tools to understand Le Roux & Rouanet 2010, "Multiple Correspondence Analysis".

I use the data set, Taste_example.xls, from Le Roux's website.

When I use _"tabcontrib"_ function, I got a similar table as Table 3.7, 3.8, and 3.9.

Then I find your calculation of ctrtot is only summing both minus modalities and plus modalities. 
But in the above Tables3.7 - 3.9, there are columns named deviation, I think these are the "contribution of deviation", p23, 
and calculation methods are explained in Table3.10, page 57.

When I use _tabcontrib_ as an aid in the interpretation of each axis,  the value of ctrtot is usefull for it. 

I would like to know your opinion about it. Is it necessary to evaluate "contribution of deviation" to interpret the axis ?

best 

kazuo

P.S 
I am using _tabcontirb_ with little modification as follows.

- to select the separatior of variable and modality, sep = 
- to get  whole contributions table, as the option to _dimcontrib_, best_f = 

```
tabcontrib2<- function (resmca, dim = 1,sep=".",best_f = TRUE) # 
{
    z <- dimcontrib(resmca, dim,best = best_f)$var[[1]]
    z$var <- unlist(lapply(strsplit(rownames(z), sep, fixed = TRUE), 
        function(x) x[1]))
    z$moda <- unlist(lapply(strsplit(rownames(z), sep, fixed = TRUE), 
        function(x) paste(x[-1], collapse = sep)))>
              :       
      (same)
```

**Comment by nicolas-robette** [comment]
It took me a lot of time to dive into it, but I've added the "contribution of deviation" to the function (although it seems to be often quite close to the total contribution). 
Thanks for the suggestion !

**Comment by 419kfj** [comment]
Thank you for your support! 
 As you wrote, "(although it seems to be often quite close to the total contribution)", I think so too.
 
 But in "Le Roux B., Rouanet H. (1998). [Interpreting Axes in MCA: Method of the contributions of points and deviations](https://helios2.mi.parisdescartes.fr/~lerb/Textes_pdf/Int_Axes.pdf), in Visualization of categorical data, ed. J. Blasius & M. Greenacre, Academic Press.", they use the term "Method of the contributions of points and deviations", and they refer to this method in other articles like MCA2010. 
 
 Is it possible to download this new tabcontirb from the GitHub archive?

**Comment by nicolas-robette** [comment]
Yes, the updated function is available in this github repo. Besides, there are many changes in the package, and I hope a brand new version will be available at CRAN in a few weeks (or months).
