### ISSUE TITLE
factor is nessesary to data ? 

### ISSUE THREAD

**Issue by 419kfj** [nicolas-robette/GDAtools#8]
In the speMCA document, I read as follow.

data | data frame with n rows (individuals) and p columns (categorical variables)

Does "p columns (categorical variables)" mean "as factor" ?

I download the Tast_example.xls data form Le Roux web site and read it by read_excel().

```
.d <- read_excel("Taste_Example.xls")
.d %>% filter(Isup=="Active") -> .d0
res.MCA <- FactoMineR::MCA(.d0[,3:6],graph=FALSE)
```
FactoMineR::MCA works.
But GDAtools::speMCA doesn't.

```
res.speMCA <- speMCA(.d0[,3:6])
```

I encountred the next error message.

```
aggregate.data.frame(as.data.frame(x), ...) Error
arguments must have same length
``` 
So I tried to convert data to factor  and tried again.
Then both FactoMineR::MCA and GDAtools::speMCA work.

So "factor" is nessesary to the data ? 

kazuo

**Comment by nicolas-robette** [comment]
Factors (and data frames instead of tibbles) were necessary, but I've just fixed this.
