### ISSUE TITLE
checking indsup function

### ISSUE THREAD

**Issue by 419kfj** [nicolas-robette/GDAtools#9]
I am using Taste_example.xls data from Le Roux's Website.

I tried to add  the taste of Oscar_wild's taste (ref: LeRoux & Rouanet 2010, p58)

I made the data as following
```
Oscar_wild <- tribble(~TV,~Film,~Art,~Eat,
                     #-------------------
                     "Tv-Drama","Horror","RenaissanceArt","Pub ")
```

And added it as a 1216 line data. 
```
.d <- read_excel("Taste_Example.xls")
.d %>% filter(Isup=="Active") -> .d0

bind_rows(.d0[,3:6],Oscar_wild) -> .d1
.d1 %>% mutate_all(.funs = factor) -> .d1.f
```

I tried indsup as folloing.
```
res.speMCA1 <- speMCA(.d1.f)
indsup(resmca = res.speMCA,supdata = .d1.f[1216,])
```

Error message is as following.

`[<-`(`*tmp*`, , j, value = 0) でエラー: 添え字が許される範囲外です

best

kazuo

**Comment by nicolas-robette** [comment]
This is because .d1.f is a tribble and not a simple data frame. I've fixed this, this should work now.
